shell = "zsh"

[plugins.oh-my-zsh]
github = "ohmyzsh/ohmyzsh"
use = ["lib/*.zsh", "plugins/git/*.zsh"]

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"
tag = "v1.20.0"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# Substring search for command history
[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

# Suggests missing commands ("you should use ... instead")
[plugins.zsh-you-should-use]
github = "MichaelAquilina/zsh-you-should-use"